job: fracture
schema: adeli

model: ../data/model_a.vtu

zone:
  type: sphere
  center: [ 25, 30, -10 ]
  radius: 1

data:
  Set A: ../data/fractures.csv
  Set B: ../data/fractures_b.csv

plot:
  title: "Fractures and Model principal directions comparison"
  figsize: [ 9, 9 ]
  dpi: 300
  data:
    markersize: 15
    alpha: 0.6
    marker: "."
  avg_directions:
    show: true
    markersize: 10
  cell_directions:
    show: true
    style: scatter
    color: "grey"
    markersize: 1
    alpha: 0.3

output:
  save_vtu: true